name: misery
channels:
  - defaults
dependencies:
  - beautifulsoup4=4.9.3
  - colorama=0.4.4
  - flask=1.1.2
  - html5lib=1.1
  - pillow=8.2.0
  - pip=21.0.1
  - python=3.9.4
  - requests=2.25.1
  - setuptools=52.0.0
  - wheel=0.36.2